### ISSUE TITLE
first example not working

### ISSUE THREAD

**Issue by magowiz** [robertsdotpm/p2pd#11]
I was trying to execute on mine system the first example, this one:
`from p2pd import *

async def example():
    # Start the default interface.
    i = await Interface().start()
    #
    # Load additional NAT details.
    # Restrict, random port NAT assumed by default.
    await i.load_nat()
    #
    # Show the interface details.
    repr(i)

if __name__ == '__main__':
    async_test(example)`
taken from this documentation page:
https://p2pd.readthedocs.io/en/latest/python/basics.html#network-interface-cards

by the way I don't get any output but these error lines:
`Task was destroyed but it is pending!
task: <Task pending name='Task-93' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-94' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-97' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-99' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-100' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
`

If I change the repr instruction with print() I can get something similar to example output:
`{'id': 'wlo1',
 'is_default': {2: True, 10: False},
 'mac': '10:51:07:16:c3:a3',
 'name': 'wlo1',
 'nat': {'delta': {'type': 2, 'value': 0},
         'delta_info': 'equal delta (local port == mapped port)',
         'nat_info': 'restrict port',
         'type': 5},
 'nic_no': 0,
 'rp': {2: [{'af': 2,
             'ext_ips': [{'af': 2, 'cidr': 32, 'ip': '2.235.120.73'}],
             'nic_ips': [{'af': 2, 'cidr': 32, 'ip': '192.168.2.130'}]}],
        10: []}}
Task was destroyed but it is pending!
task: <Task pending name='Task-93' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-94' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-97' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-99' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-100' coro=<nat_test_workers.<locals>.worker() done, defined at /home/magowiz/venvs3/share_soul/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>

Process finished with exit code 0
`
is it ok like this ? Can I safely use print instead of repr and ignore these errors ?

**Comment by robertsdotpm** [comment]
Yes, the code should have used print and not repr. Will update that.
