### ISSUE TITLE
TypeError: start_p2p_node() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by hmxustin** [robertsdotpm/p2pd#22]
Trying to execute the example on the page https://p2pd.readthedocs.io/en/latest/python/p2p.html , I encounter the TypeError error: start_p2p_node() got an unexpected keyword argument 'seed'. When trying to inspect the code of the start_p2p_node method, I really don't find the seed argument there... Perhaps it makes sense to remove this fragment from the example.

upd.: The sample code shown on this page does not work at all... It "freezes" for a while, and then the AttributeError error appears: 'SqliteKVS' object has no attribute 'db'

**Comment by robertsdotpm** [comment]
fixed, will update docs in the coming weeks
