### ISSUE TITLE
p2p node could not load ifs - when running inside FastAPI app

### ISSUE THREAD

**Issue by WojciechSzade** [robertsdotpm/p2pd#23]
Hey man, I wanted to integrate your library to run along a FastAPI app, so I could use them at once.   
Your demo runs just fine on my pc, in the same python venv the app is running in.   
Running it in a shell works fine as well:  
```
from p2pd import *
 async def example():
     node = await P2PNode()  

 async def start():
     await example()
 
start()
<coroutine object start at 0x7381ae4a1e40>
```  
  
 However, when I try to run it in my FastAPI app it gives me the following error:  
 
`poetry run fastapi dev src/main.py`
> ERROR:    Traceback (most recent call last):
  File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/szade/Documents/Studia/Projekt dyplomowy/src/main.py", line 17, in lifespan
    await app.state.node.start()
  File "/home/szade/Documents/Studia/Projekt dyplomowy/src/peer/peer.py", line 21, in start
    self.node = await P2PNode()
                ^^^^^^^^^^^^^^^
  File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/p2p_node.py", line 114, in start
    raise Exception("p2p node could not load ifs.")
Exception: p2p node could not load ifs.
ERROR:    Application startup failed. Exiting.  

The code for main.py is:  
```
from fastapi import FastAPI
from contextlib import asynccontextmanager
import uvicorn

from src.core.db import init_db
from src.core.models import BlockchainService
from src.core.config import settings
from src.api.routers import router
from src.peer.peer import NodeService, IPManager

@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.ipmanager = IPManager("ip_list.txt")
    app.state.node = NodeService(app.state.ipmanager)
    await app.state.node.start()
    yield
    await app.state.node.stop()

app = FastAPI(
    lifespan=lifespan,
    title=settings.PROJECT_NAME,
)

def get_blockchain():
    return app.state.blockchain

app.include_router(router)

if __name__ == "__main__":
    uvicorn.run(app)
```  
And the peer/peer.py code is:  
```
import logging
from p2pd import *

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class IPManager:
    def __init__(self, filename):
        self.filename = filename
        self.ip_list = []

    def get_ip_list(self):
        with open(self.filename, "r") as f:
            self.ip_list = f.readlines()
        return self.ip_list

class NodeService:
    def __init__(self, ipmanager: IPManager):
        self.ipmanager = ipmanager
    async def start(self):
        self.node = await P2PNode()
        # self.pipes = []
        # for ip in self.ipmanager.get_ip_list():
        #     try:
        #         self.pipes.append(await self.node.connect(ip))
        #         logger.info(f"Connected to {ip}")
        #     except Exception as e:
        #         logger.error(f"Failed to connect to {ip}: {e}")
        #         continue
            
    async def stop(self):
        await self.node.close()
```  
  
 I've followed this thread to run the two apps at once:  
 https://stackoverflow.com/questions/76142431/how-to-run-another-application-within-the-same-running-event-loop  
   
   I'll be glad for any help - maybe I am misunderstanding something.

**Comment by robertsdotpm** [comment]
Hey man,

I checked out the link in the stackoverflow thread about the person trying to use FastAPI. What stood out to me is their bot thing mixes threading with asyncio and multiple event loops which you almost never want to do. You want to keep things simple. One event loop can run many, many tasks 'concurrently' -- it won't 'block' the program for I/O. Try not to use threads at all, in fact.

I've adapted the stackoverflow suggestions to show how you might start to use FastAPI + uvicorn + P2PD. Note that I'm using older asyncio funcs for more compatibility with older Python versions. Mixing the asyncio context manager has caused me problems in the past too, so I've avoided it here. Hopefully this gives you some idea how to continue your project.

```python3
# P2PD import here comes first.
# It will specify some settings for the event loop that it needs.
from p2pd import *
from fastapi import FastAPI
import uvicorn

# Web app and server task.
app = FastAPI()
fastapi_serv_task = None

# FastAPI is used as the web framework.
@app.get("/")
async def read_root():
    return {"Hello": "World"}

async def entry():
    # Use uvicorn as the web server.
    config = uvicorn.Config(app)
    server = uvicorn.Server(config)

    # The web server is made to run 'in the background.'
    # I save the 'task' to avoid garbage collection.
    fastapi_serv_task = asyncio.ensure_future(
        server.serve()
    )

    # Start a new P2P node with your protocol.
    # The P2PD node already runs in the background like above.
    node = await P2PNode()
    print("node started")
    print(node.ifs)

    # Put the rest of your app code here. 
    # None of the above is blocking.
    # Lines below are to stop the program from ending.
    # You would prob want something more efficient than this.
    while 1:
        await asyncio.sleep(0.01)

# Old school way to run a coroutine.
# Works well for older Python versions.
loop = asyncio.get_event_loop()
loop.run_until_complete(entry())
```

**Comment by robertsdotpm** [comment]
The changes I'd make to it would be something like this:

- Use asyncio.run(entry()). This is a much higher-level function for running coroutines and it handles cleanup better than run_until_complete. Available in more recent python versions. This is how you're 'meant' to run coroutines in modern Python.
- Instead of the while ... await asyncio.sleep you could do something like this: 

close_signal = asyncio.Event()
await close_signal.wait()

Basically, what this says is -- wait until the close_signal is set -- which in this case is never set by anything. i.e. the equivalent of async blocking. You could set it by calling close_signal.set() later on -- for instance you might register a signal handler for control + c and then have it call close_signal.set() to automatically make your main coroutine end. But the purpose here is to keep the entry point coroutine alive instead of using the while ... sleep for that. 

I mean, if you wanted to make this a little neater I'd probably also put it in a class. Make something that represents a feature of your program -- maybe in this case its your REST api section -- and put the code in there. You would particularly benefit from having the global variables in the __init__ function. Then that feature is neat and can even be parsed around the rest of your program.

**Comment by WojciechSzade** [comment]
Thank you very much for your help - now the app works perfectly and looks neat - all thanks to you.

**Comment by WojciechSzade** [comment]
Hey uhm - actually, the issue that I originally described still occurs. In my app it happens every couple runs, and adding a retry decorator took care of it - it starts every couple times, but to my surprise it even happened with the demo, while my app wasn't even running. Posting the logs below. Keep in mind it doesn't happen every time.  
   
   
 `poetry run python -m p2pd.demo`   
 
> /home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/demo.py:262: DeprecationWarning: There is no current event loop
>   loop = asyncio.get_event_loop()
> Universal reachability demo
> Coded by matthew@roberts.pm
> -----------------------------
> 
> Loading networking interfaces...
> 
> Starting node...
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/demo.py", line 263, in <module>
>     loop.run_until_complete(main())
>   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/demo.py", line 71, in main
>     await node.start(out=True)
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/p2p_node.py", line 114, in start
>     raise Exception("p2p node could not load ifs.")
> Exception: p2p node could not load ifs.  
  
 
My specs are:  
```
szade@arch-legion
-----------------
OS: Arch Linux x86_64
Host: 82RG (Legion 5 Pro 16ARH7H)
Kernel: Linux 6.12.4-arch1-1
Uptime: 44 mins
Packages: 1331 (pacman), 6 (flatpak)
Shell: zsh 5.9
Resolution: 2560x1600 1920x1080 2560x1440
DE: GNOME 47.2
WM: Mutter (Wayland)
WM Theme: default-pure
Theme: Adwaita [GTK2/3/4]
Icons: Adwaita [GTK2/3/4]
Terminal: tilix 1.9.6
Terminal Font: AnonymicePro Nerd Font 11
CPU: AMD Ryzen 7 6800H (16) @ 4.79 GHz
GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU [Discrete]
GPU: AMD Radeon 680M [Integrated]
Memory: 9022 MiB / 31274 MiB
```
And my ip -br a gives:  
```
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp4s0           UP             192.XXX.X.XX/24 fe80::633c:XXXX:XXXX:XXXX/64 
wlan0            DOWN           
docker0          DOWN           172.17.0.1/16 
br-e8d5790fbc95  DOWN           172.18.0.1/16 
br-f1175a90ba4d  DOWN           172.23.0.1/16 
br-2f0560140185  DOWN           172.20.0.1/16 
br-40b588801a78  DOWN           172.24.0.1/16 
br-4ad0064214ef  DOWN           172.19.0.1/16 
br-5e7e82b416eb  DOWN           172.21.0.1/16 
br-9afa5bc0b809  DOWN           172.22.0.1/16 
```

**Comment by WojciechSzade** [comment]
I think you're right and the issue is with the STUN servers.   
program.log gives basically this issue over and over: 

> utils.py:45] Starting resolve with stack type = 1337
> [utils.py:45] Load if info = wlan0
> [utils.py:45] Attempting to resolve 2
> [utils.py:45] wlan0 2 False
> [utils.py:45] Attempting to resolve 10
> [utils.py:45] wlan0 10 False
> [utils.py:45] > interface.py, line 812 = Traceback (most recent call last):
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/interface.py", line 812, in load_interfaces
>     nic = await Interface(if_name)
>           ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/interface.py", line 501, in start
>     return await self.do_start(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/szade/.cache/pypoetry/virtualenvs/dpachain-PfhLflEr-py3.12/lib/python3.12/site-packages/p2pd/interface.py", line 482, in do_start
>     assert(self.stack in VALID_STACKS)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError

 
 Here is the whole log:
https://pastebin.com/HScQEBe2  
By the way, I am also honestly struggling to make a working piece of code with this library.  
I think adding a short quickstart section to the docs would make it easier for everyone.  
Currently I am just basing my code on the demo.py, as it works properly.  
But could you write the most simple code, that does the following:  
1st code for: Start a node on defined port, register it with a defined nickname.  
2st code for: Start a node on defined port, register it with a defined nickname, connect to the node started in another instance, send any message.  
I'm having issue understanding which parts of your demo code are for printing purposes and which are actually required to run such a task.   
When I tried doing a similar task, running a registered test.peer node in your demo and starting my own trying to send a message, I for example got something like this - and I didn't see no message.  

INFO:src.

> peer.nodes:    enp4s0 (v4)
> INFO:src.peer.nodes:Creating node...
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 1 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.client:[SUBACK] 1 (2,)
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 2 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 2 (2,)
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 3 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 3 (2,)
> INFO:src.peer.nodes:Node created
>         Loading STUN clients...
>                 Loaded (done)
>         Loading MQTT clients...
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 4 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> WARNING:p2pd.gmqtt.mqtt.protocol:[TRYING WRITE TO CLOSED SOCKET]
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 5 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 4 (2,)
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.client:[SUBACK] 5 (2,)
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 6 [b'27a585f0ef2df3891731bf286']
>         Loading NTP clock skew...
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> WARNING:p2pd.gmqtt.mqtt.protocol:[TRYING WRITE TO CLOSED SOCKET]
> INFO:p2pd.gmqtt.client:[SUBACK] 6 (2,)
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 7 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 7 (2,)
>                 Clock skew = 0
>         Starting UPnP task...
> INFO:src.peer.nodes:Node started = b'5,6,2,4-[1,0,188.146.130.152,192.168.1.46,44666,6,6,0]-0-27a585f0ef2df3891731bf286-242be2869342577c0080c5eb9dd2b9e0a1f9c68dc06e8f8bb0995a0e7d5018a2'
> INFO:src.peer.nodes:Node port = 44666
> INFO:src.peer.nodes:Starting call to 'src.peer.nodes.NodeService._connect_to_nodes', this is the 1st time calling it.
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 8 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 8 (2,)
> INFO:src.peer.nodes:Connected to test.peer
> INFO:src.peer.nodes:Sent message to test.peer
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 11 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> WARNING:p2pd.gmqtt.mqtt.protocol:[TRYING WRITE TO CLOSED SOCKET]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 12 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> WARNING:p2pd.gmqtt.mqtt.protocol:[TRYING WRITE TO CLOSED SOCKET]
> INFO:p2pd.gmqtt.client:[SUBACK] 12 (2,)
> INFO:p2pd.gmqtt.client:[SUBACK] 11 (2,)
> INFO:p2pd.gmqtt.mqtt.protocol:[CONNECTION MADE]
> INFO:p2pd.gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
> INFO:p2pd.gmqtt.mqtt.package:[SEND SUB] 13 [b'27a585f0ef2df3891731bf286']
> INFO:p2pd.gmqtt.client:[SUBACK] 13 (2,)
  
 My code looks like this:  
 ```class NodeService:
    def __init__(self, ipmanager: IPManager):
        self.ipmanager = ipmanager

    async def start(self, port):
        self.node = await self._create_node(port)
        self.pipes = []
        await self._connect_to_nodes()
        
        

    @retry(
        stop=stop_after_attempt(max_tries),
        before=before_log(logger, logging.INFO),
        after=after_log(logger, logging.WARN),
        before_sleep=before_sleep_log(logger, logging.INFO)
    )
    async def _create_node(self, port):
        try:
            if_names = await list_interfaces()
            ifs = await load_interfaces(if_names)
            buf = ""
            for nic in ifs:
                buf += fstr("\t{0} ", (nic.name,))
                for af in nic.supported():
                    if af == IP4:
                        buf += "(v4)"
                    if af == IP6:
                        buf += "(v6)"
                buf += "\n"
            logger.info(buf[:-1])
            logger.info("Creating node...")
            node = await P2PNode(port=port, ifs=ifs)
            logger.info("Node created")
            # node_name = await node.nickname("node")
            # logger.info(f"Node name: {node_name}")
            node.add_msg_cb(self._add_echo_support)
            await node.start(out=True)
            logger.info(f"Node started = {node.addr_bytes}")
            logger.info(f"Node port = {node.listen_port}",)
            return node
            
        except Exception as e:
            logger.error(f"Failed to create node: {e}")
            raise e

    @retry(
        stop=stop_after_attempt(max_tries),
        before=before_log(logger, logging.INFO),
        after=after_log(logger, logging.WARN),
        before_sleep=before_sleep_log(logger, logging.INFO)
    )
    async def _connect_to_nodes(self):
        for ip in self.ipmanager.get_ip_list():
            try:
                self.pipes.append(await self.node.connect(ip))
                logger.info(f"Connected to {ip}")
                await self.pipes[-1].send(b"Hello world!")
                logger.info(f"Sent message to {ip}")
                # buf = await self.pipes[-1].recv()
                # logger.info(f"Received message from {ip}: {buf}")
            except Exception as e:
                logger.error(f"Failed to connect to {ip}: {e}")
                continue

    async def stop(self):
        await self.node.close()
        
    async def _add_echo_support(self, msg, client_tup, pipe):
        if b"ECHO" == msg[:4]:
            print()
            print("\tGot echo proto msg: " + to_s(msg) + fstr(" from {0}", (client_tup,)))
            print()
            await pipe.send(msg[4:], client_tup)
```

**Comment by robertsdotpm** [comment]
The node.connect function is designed to use the special P2P address of a node. It doesn't take a regular IP. E.g. to get this address you call node.address() then pass it to connect. This is explained in https://p2pd.readthedocs.io/en/latest/p2p/nicknames.html You can use addresses for nodes (very inconvenient) or give a node a nickname that can easily be shared with other nodes. 

By the way: your idea to try test it out with the echo protocol won't work. The echo handler is checking that the first segment has 'ECHO ' in the message. So you need to send 'ECHO hello world\n' down the pipe. If you want to get a response. 

For best results though you should have node_a call connect to node_b and not try to do something like self-connections. Cause I haven't tested that much. Talking to you about this I do get how the docs need to be expanded to show this usage. It's really hard to write docs from like a 'first usage perspective' since I no longer have one.

**Comment by WojciechSzade** [comment]
I actually understood the part about the nicknames and IP addresses (I think). The ip_list actually contains 'test.peer', but I get how I made that fairly confusing.  
I maybe didn't explain what I am doing properly: my app starts an unnamed node, and then it calls node.connect('test.peer').  
test.peer is started on the demo and on listening mode.  
I don't understand the self-connect part?  
Should I not call node.connect() on my own node, and rather create another P2PNode, don't run .start() and run connect() instead, or what?  
  
  I understand the first usage perspective issue - I can try to give you some feedback as one, maybe even write something if I will finally understand it myself.

**Comment by robertsdotpm** [comment]
So in the demo app it will create a node and automatically register a (very) unfriendly name for it. The name will be based on a public key. All of this is guaranteed to be unique (and deterministically tied to port and computer name) so its useful for testing.

To be able to update a a nodes name with its address you need to have the private key that belongs to that name. For 'test' I think I might have used that name already (would be surprised if I haven't.) But yeah -- the next step in the demo console would be to put it into listen mode with accept (like you've done.) And then copy that nodes nickname to use for your connect call in the code you already have. E.g. mine looks like 234342341231234532.peer. Make sure to include the '.peer' part (or whatever .tld you get.)

**Comment by WojciechSzade** [comment]
holy shit hah, I got your message :P

**Comment by robertsdotpm** [comment]
That was reverse connect. On my machine the software managed to port forward for me and told your server to connect back to me. I was honestly just curious what test.peer resolved to. But I guess you're right -- it belongs to you.

**Comment by robertsdotpm** [comment]
If you send me just the skeleton of your app (you can delete all the API methods or something) I can look into trying to get it to work for you tomorrow.

**Comment by WojciechSzade** [comment]
Just tell me what's wrong with this....  
```
class NodeService:
    def __init__(self, ipmanager: IPManager):
        self.ipmanager = ipmanager

    async def start(self, port):
        self.node = await self._create_node(port)
        self.pipes = []
        await self._connect_to_nodes()
        
        

    @retry(
        stop=stop_after_attempt(max_tries),
        before=before_log(logger, logging.INFO),
        after=after_log(logger, logging.WARN),
        before_sleep=before_sleep_log(logger, logging.INFO)
    )
    async def _create_node(self, port):
        try:
            logger.info("Creating node...")
            node = await P2PNode(port=port)
            logger.info("Node created")
            # node_name = await node.nickname("node")
            # logger.info(f"Node name: {node_name}")
            node.add_msg_cb(self._add_echo_support)
            await node.start(out=True)
            logger.info(f"Node started = {node.addr_bytes}")
            logger.info(f"Node port = {node.listen_port}",)
            return node
            
        except Exception as e:
            logger.error(f"Failed to create node: {e}")
            raise e

    @retry(
        stop=stop_after_attempt(max_tries),
        before=before_log(logger, logging.INFO),
        after=after_log(logger, logging.WARN),
        before_sleep=before_sleep_log(logger, logging.INFO)
    )
    async def _connect_to_nodes(self):
        # for ip in self.ipmanager.get_ip_list():
        #     try:
        #         node_addr = self.node.address(ip)
        #         self.pipes.append(await self.node.connect(node_addr))
        #         logger.info(f"Connected to {ip}")
        #         await self.pipes[-1].send(b"ECHO hello world\r\n")
        #         logger.info(f"Sent message to {ip}")
        #         buf = await self.pipes[-1].recv()
        #         logger.info(f"Received message from {ip}: {buf}")
        #     except Exception as e:
        #         logger.error(f"Failed to connect to {ip}: {e}")
        #         continue
        pipe = await self.node.connect("test.peer")
        await pipe.send(b"ECHO hello world\r\n")
        buf = await pipe.recv(timeout=3)
        print("Got echo response: ", buf)

    async def stop(self):
        await self.node.close()
        
    async def _add_echo_support(self, msg, client_tup, pipe):
        if b"ECHO" == msg[:4]:
            print()
            print("\tGot echo proto msg: " + to_s(msg) + fstr(" from {0}", (client_tup,)))
            print()
            await pipe.send(msg[4:], client_tup)
            ```

**Comment by robertsdotpm** [comment]
node = await P2PNode(port=port)
            logger.info("Node created")
            # node_name = await node.nickname("node")
            # logger.info(f"Node name: {node_name}")
            node.add_msg_cb(self._add_echo_support)
            await node.start(out=True)
            
            This stands out to me. await P2PNode is the same as calling node.start -- and very bad things are likely to happen if you call start twice. If thats the problem the fix is easy:
            
            # Delete await
             node = P2PNode(port=port)
            logger.info("Node created")
            # node_name = await node.nickname("node")
            # logger.info(f"Node name: {node_name}")
            node.add_msg_cb(self._add_echo_support)
            await node.start(out=True)

Otherwise will have to look tomorrow cause its like 1 am, lol.

**Comment by WojciechSzade** [comment]
Started working instantly. Thank you so much.

**Comment by robertsdotpm** [comment]
Issue solved or can I close?

**Comment by WojciechSzade** [comment]
LGTM
