### ISSUE TITLE
Error when running node.register()

### ISSUE THREAD

**Issue by blue-spirits** [robertsdotpm/p2pd#5]
I tried to run the sample code on https://p2pd.readthedocs.io/en/latest/python/index.html
`...`
`await node.register(PDNS_NAME)`
`...`
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/lib/python3.10/site-packages/scripts/kvs_schema.sqlite3'

**Comment by robertsdotpm** [comment]
What is the output of ls '/home/user/.local/lib/python3.10/site-packages/scripts' and what version of p2pd are you on?

**Comment by robertsdotpm** [comment]
Looks like the scripts dir just wasn't pushed with the package. Will get this sorted in a moment.

**Comment by robertsdotpm** [comment]
Hello, I've made changes to have the scripts dir included in the package and fixed some small bugs when I was testing. You can update to the most recent package with python3 -m pip install --upgrade p2pd. Let me know how it goes. The 'dns' feature uses an unstable free hosting service so it may not be 100% reliable. Still working on a better way to test all this so it may be buggy. But I try to fix bugs fast. Cheers.

**Comment by blue-spirits** [comment]
I run` python3 -m pip install --upgrade p2pd` and still get the error,

**Comment by blue-spirits** [comment]
I copied the scripts folder from the source code to /home/user/.local/lib/python3.10/site-packages/ and it worked.

**Comment by robertsdotpm** [comment]
Did you install p2pd from pypi initially or by cloning on Github and running setup.py install?

**Comment by blue-spirits** [comment]
> 您最初是从 pypi 安装 p2pd 还是通过在 Github 上克隆并运行 setup.py install 来安装 p2pd？

pypi

**Comment by robertsdotpm** [comment]
Thanks, the setup.py wasn't copying the file. I install the package using developer mode so didn't realize. Should be solved now.
